const mongoose = require('mongoose');

/**
 * A single bookable slot for a barber on a given date.
 * Slots are generated by the owner (or auto-generated from business hours)
 * and consumed by bookings.
 */
const timeSlotSchema = new mongoose.Schema(
  {
    salon: { type: mongoose.Schema.Types.ObjectId, ref: 'Salon', required: true },
    barber: { type: mongoose.Schema.Types.ObjectId, ref: 'Barber', required: true },
    date: { type: String, required: true }, // "YYYY-MM-DD"
    startTime: { type: String, required: true }, // "HH:mm"
    endTime: { type: String, required: true },
    isBooked: { type: Boolean, default: false },
    booking: { type: mongoose.Schema.Types.ObjectId, ref: 'Booking', default: null },
  },
  { timestamps: true }
);

timeSlotSchema.index({ barber: 1, date: 1, startTime: 1 }, { unique: true });

module.exports = mongoose.model('TimeSlot', timeSlotSchema);
